/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAdminRouteImport } from './routes/admin/_admin'
import { Route as clientLayoutRouteImport } from './routes/(client)/_layout'
import { Route as AdminAdminIndexRouteImport } from './routes/admin/_admin/index'
import { Route as clientLayoutIndexRouteImport } from './routes/(client)/_layout/index'
import { Route as clientLayoutContactRouteImport } from './routes/(client)/_layout/contact'
import { Route as clientLayoutAboutRouteImport } from './routes/(client)/_layout/about'
import { Route as AdminAdminSettingsIndexRouteImport } from './routes/admin/_admin/settings/index'
import { Route as AdminAdminProductsIndexRouteImport } from './routes/admin/_admin/products/index'
import { Route as clientLayoutProductsIndexRouteImport } from './routes/(client)/_layout/products/index'
import { Route as clientLayoutBlogsIndexRouteImport } from './routes/(client)/_layout/blogs/index'
import { Route as AdminAdminProductsProductIdRouteImport } from './routes/admin/_admin/products/$productId'
import { Route as clientLayoutProductsProductIdRouteImport } from './routes/(client)/_layout/products/$productId'
import { Route as clientLayoutBlogsBlogIdRouteImport } from './routes/(client)/_layout/blogs/$blogId'

const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin/_admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const clientLayoutRoute = clientLayoutRouteImport.update({
  id: '/(client)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const clientLayoutIndexRoute = clientLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => clientLayoutRoute,
} as any)
const clientLayoutContactRoute = clientLayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => clientLayoutRoute,
} as any)
const clientLayoutAboutRoute = clientLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => clientLayoutRoute,
} as any)
const AdminAdminSettingsIndexRoute = AdminAdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminProductsIndexRoute = AdminAdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const clientLayoutProductsIndexRoute =
  clientLayoutProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => clientLayoutRoute,
  } as any)
const clientLayoutBlogsIndexRoute = clientLayoutBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => clientLayoutRoute,
} as any)
const AdminAdminProductsProductIdRoute =
  AdminAdminProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const clientLayoutProductsProductIdRoute =
  clientLayoutProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => clientLayoutRoute,
  } as any)
const clientLayoutBlogsBlogIdRoute = clientLayoutBlogsBlogIdRouteImport.update({
  id: '/blogs/$blogId',
  path: '/blogs/$blogId',
  getParentRoute: () => clientLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/about': typeof clientLayoutAboutRoute
  '/contact': typeof clientLayoutContactRoute
  '/': typeof clientLayoutIndexRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/blogs/$blogId': typeof clientLayoutBlogsBlogIdRoute
  '/products/$productId': typeof clientLayoutProductsProductIdRoute
  '/admin/products/$productId': typeof AdminAdminProductsProductIdRoute
  '/blogs': typeof clientLayoutBlogsIndexRoute
  '/products': typeof clientLayoutProductsIndexRoute
  '/admin/products': typeof AdminAdminProductsIndexRoute
  '/admin/settings': typeof AdminAdminSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/admin/login': typeof AdminLoginRoute
  '/about': typeof clientLayoutAboutRoute
  '/contact': typeof clientLayoutContactRoute
  '/': typeof clientLayoutIndexRoute
  '/admin': typeof AdminAdminIndexRoute
  '/blogs/$blogId': typeof clientLayoutBlogsBlogIdRoute
  '/products/$productId': typeof clientLayoutProductsProductIdRoute
  '/admin/products/$productId': typeof AdminAdminProductsProductIdRoute
  '/blogs': typeof clientLayoutBlogsIndexRoute
  '/products': typeof clientLayoutProductsIndexRoute
  '/admin/products': typeof AdminAdminProductsIndexRoute
  '/admin/settings': typeof AdminAdminSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(client)/_layout': typeof clientLayoutRouteWithChildren
  '/admin/_admin': typeof AdminAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/(client)/_layout/about': typeof clientLayoutAboutRoute
  '/(client)/_layout/contact': typeof clientLayoutContactRoute
  '/(client)/_layout/': typeof clientLayoutIndexRoute
  '/admin/_admin/': typeof AdminAdminIndexRoute
  '/(client)/_layout/blogs/$blogId': typeof clientLayoutBlogsBlogIdRoute
  '/(client)/_layout/products/$productId': typeof clientLayoutProductsProductIdRoute
  '/admin/_admin/products/$productId': typeof AdminAdminProductsProductIdRoute
  '/(client)/_layout/blogs/': typeof clientLayoutBlogsIndexRoute
  '/(client)/_layout/products/': typeof clientLayoutProductsIndexRoute
  '/admin/_admin/products/': typeof AdminAdminProductsIndexRoute
  '/admin/_admin/settings/': typeof AdminAdminSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/admin/login'
    | '/about'
    | '/contact'
    | '/'
    | '/admin/'
    | '/blogs/$blogId'
    | '/products/$productId'
    | '/admin/products/$productId'
    | '/blogs'
    | '/products'
    | '/admin/products'
    | '/admin/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/login'
    | '/about'
    | '/contact'
    | '/'
    | '/admin'
    | '/blogs/$blogId'
    | '/products/$productId'
    | '/admin/products/$productId'
    | '/blogs'
    | '/products'
    | '/admin/products'
    | '/admin/settings'
  id:
    | '__root__'
    | '/(client)/_layout'
    | '/admin/_admin'
    | '/admin/login'
    | '/(client)/_layout/about'
    | '/(client)/_layout/contact'
    | '/(client)/_layout/'
    | '/admin/_admin/'
    | '/(client)/_layout/blogs/$blogId'
    | '/(client)/_layout/products/$productId'
    | '/admin/_admin/products/$productId'
    | '/(client)/_layout/blogs/'
    | '/(client)/_layout/products/'
    | '/admin/_admin/products/'
    | '/admin/_admin/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  clientLayoutRoute: typeof clientLayoutRouteWithChildren
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(client)/_layout': {
      id: '/(client)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof clientLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin/': {
      id: '/admin/_admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/(client)/_layout/': {
      id: '/(client)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof clientLayoutIndexRouteImport
      parentRoute: typeof clientLayoutRoute
    }
    '/(client)/_layout/contact': {
      id: '/(client)/_layout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof clientLayoutContactRouteImport
      parentRoute: typeof clientLayoutRoute
    }
    '/(client)/_layout/about': {
      id: '/(client)/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof clientLayoutAboutRouteImport
      parentRoute: typeof clientLayoutRoute
    }
    '/admin/_admin/settings/': {
      id: '/admin/_admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/products/': {
      id: '/admin/_admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAdminProductsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/(client)/_layout/products/': {
      id: '/(client)/_layout/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof clientLayoutProductsIndexRouteImport
      parentRoute: typeof clientLayoutRoute
    }
    '/(client)/_layout/blogs/': {
      id: '/(client)/_layout/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof clientLayoutBlogsIndexRouteImport
      parentRoute: typeof clientLayoutRoute
    }
    '/admin/_admin/products/$productId': {
      id: '/admin/_admin/products/$productId'
      path: '/products/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminAdminProductsProductIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/(client)/_layout/products/$productId': {
      id: '/(client)/_layout/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof clientLayoutProductsProductIdRouteImport
      parentRoute: typeof clientLayoutRoute
    }
    '/(client)/_layout/blogs/$blogId': {
      id: '/(client)/_layout/blogs/$blogId'
      path: '/blogs/$blogId'
      fullPath: '/blogs/$blogId'
      preLoaderRoute: typeof clientLayoutBlogsBlogIdRouteImport
      parentRoute: typeof clientLayoutRoute
    }
  }
}

interface clientLayoutRouteChildren {
  clientLayoutAboutRoute: typeof clientLayoutAboutRoute
  clientLayoutContactRoute: typeof clientLayoutContactRoute
  clientLayoutIndexRoute: typeof clientLayoutIndexRoute
  clientLayoutBlogsBlogIdRoute: typeof clientLayoutBlogsBlogIdRoute
  clientLayoutProductsProductIdRoute: typeof clientLayoutProductsProductIdRoute
  clientLayoutBlogsIndexRoute: typeof clientLayoutBlogsIndexRoute
  clientLayoutProductsIndexRoute: typeof clientLayoutProductsIndexRoute
}

const clientLayoutRouteChildren: clientLayoutRouteChildren = {
  clientLayoutAboutRoute: clientLayoutAboutRoute,
  clientLayoutContactRoute: clientLayoutContactRoute,
  clientLayoutIndexRoute: clientLayoutIndexRoute,
  clientLayoutBlogsBlogIdRoute: clientLayoutBlogsBlogIdRoute,
  clientLayoutProductsProductIdRoute: clientLayoutProductsProductIdRoute,
  clientLayoutBlogsIndexRoute: clientLayoutBlogsIndexRoute,
  clientLayoutProductsIndexRoute: clientLayoutProductsIndexRoute,
}

const clientLayoutRouteWithChildren = clientLayoutRoute._addFileChildren(
  clientLayoutRouteChildren,
)

interface AdminAdminRouteChildren {
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminProductsProductIdRoute: typeof AdminAdminProductsProductIdRoute
  AdminAdminProductsIndexRoute: typeof AdminAdminProductsIndexRoute
  AdminAdminSettingsIndexRoute: typeof AdminAdminSettingsIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminProductsProductIdRoute: AdminAdminProductsProductIdRoute,
  AdminAdminProductsIndexRoute: AdminAdminProductsIndexRoute,
  AdminAdminSettingsIndexRoute: AdminAdminSettingsIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  clientLayoutRoute: clientLayoutRouteWithChildren,
  AdminAdminRoute: AdminAdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
