// @ts-nocheck

// This file is auto-generated by the TanStack Router plugin
// Do not edit this file directly

import { createRouter as createTanStackRouter } from '@tanstack/react-router'

// Import the generated route tree
import { routeTree } from './routeTree.gen'

// Create the router using the generated route tree
export function createRouter() {
  return createTanStackRouter({
    routeTree,
    scrollRestoration: true, // Enable this
    //  basepath: '/my-app' 
     basepath: '/' 
  })
}

// Register the router instance for type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof createRouter>
  }
}